SET GLOBAL FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS `EMPLOYMENT_CONTRACT`;
DROP TABLE IF EXISTS `EMPLOYEE`;
DROP TABLE IF EXISTS `USER`;
DROP TABLE IF EXISTS `COMPANY`;
DROP TABLE IF EXISTS `PAY_SLIP`;

CREATE TABLE `EMPLOYMENT_CONTRACT` (
    `id` INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    `id_employee` INT(11) NOT NULL,
    `id_company` INT(11) NOT NULL,
    `start_date` DATE NOT NULL,
    `end_date` DATE NOT NULL
);

CREATE TABLE `USER` (
    `id` INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    `last_name` VARCHAR(255) NOT NULL,
    `first_name` VARCHAR(255) NOT NULL,
    `email` VARCHAR(255) NOT NULL,
    `password` VARCHAR(255) NOT NULL,
    `author_id` tinyint(1) NOT NULL DEFAULT '1',
    `created` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE `COMPANY` (
    `id` INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    `id_user` INT(11) NOT NULL,
    `name` VARCHAR(255) NOT NULL,
    `address` VARCHAR(255) NOT NULL
);

CREATE TABLE `EMPLOYEE` (
    `id` INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    `id_company` INT(11) NOT NULL,
    `last_name` VARCHAR(255) NOT NULL,
    `first_name` VARCHAR(255) NOT NULL,
    `address` VARCHAR(255) NOT NULL,
    `city` VARCHAR(255) NOT NULL,
    `phone` VARCHAR(255) NOT NULL,
    `state` VARCHAR(255) NOT NULL
);

CREATE TABLE `PAY_SLIP` (
    `id` INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    `id_employee` INT(11) NOT NULL, 
    `salary` INT(11) NOT NULL,
    `hours_worked` INT(11) NOT NULL,
    `net_to_pay` INT(11) NOT NULL
);

ALTER TABLE `EMPLOYMENT_CONTRACT` ADD FOREIGN KEY (`id_company`) REFERENCES `COMPANY`(`id`);
ALTER TABLE `EMPLOYEE` ADD FOREIGN KEY (`id_company`) REFERENCES `COMPANY`(`id`);
ALTER TABLE `COMPANY` ADD FOREIGN KEY (`id_user`) REFERENCES `USER`(`id`);
ALTER TABLE `PAY_SLIP` ADD FOREIGN KEY (`id_employee`) REFERENCES `EMPLOYEE`(`id`);

